SET FOREIGN_KEY_CHECKS=0;
delete from Privilege;
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(1, '2011-09-29', 0, 'user', 'create user', 'създава потребител');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(2, '2011-09-29', 1, 'user', 'delete user', 'изтрива потребител');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(3, '2011-09-29', 2, 'user', 'modify user', 'променя потребител');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(4, '2011-09-29', 3, 'forum', 'add comment', 'добавя коментар');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(5, '2011-09-29', 4, 'forum', 'delete comment', 'изтрива коментар');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(6, '2011-09-29', 5, 'forum', 'modify comment', 'променя коментар');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(7, '2011-09-29', 6, 'forum', 'search comment', 'търси коментар');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(8, '2011-09-29', 7, 'forum', 'modify post', 'променя тема');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(9, '2011-09-29', 8, 'forum', 'add post', 'добавя тема');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(10, '2011-09-29', 9, 'forum', 'delete post', 'изтрива тема');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(11, '2011-09-29', 10, 'forum', 'search post', 'търси тема');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(12, '2011-09-29', 11, 'FAQ', 'search FAQ', 'търси във ''въпроси и отговори''');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(13, '2011-09-29', 12, 'FAQ', 'add FAQ', 'добавя  във ''въпроси и отговори''');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(14, '2011-09-29', 13, 'FAQ', 'delete FAQ', 'изтрива  във ''въпроси и отговори''');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(15, '2011-09-29', 14, 'FAQ', 'modify FAQ', 'Променя ''въпроси и отговори''');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(16, '2011-09-29', 15, 'issue', 'create issue', 'създава задача');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(17, '2011-09-29', 16, 'issue', 'delete issue', 'изтрива задача');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(18, '2011-09-29', 17, 'issue', 'modify issue', 'променя задача');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(19, '2011-09-29', 18, 'issue', 'search issue', 'търси задача');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(20, '2011-09-29', 19, 'project', 'search project', 'търси проект');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(21, '2011-09-29', 20, 'project', 'create project', 'създава проект');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(22, '2011-09-29', 21, 'project', 'delete project', 'изтрива проект');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(23, '2011-09-29', 22, 'project', 'modify project', 'променя проект');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(24, '2011-09-29', 23, 'shop', 'add product', 'добавя продукт');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(25, '2011-09-29', 24, 'shop', 'delete product', 'изтрива продукт');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(26, '2011-09-29', 25, 'shop', 'modify product', 'променя продукт');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(27, '2011-09-29', 26, 'shop', 'buy product', 'купува продукт');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(28, '2011-09-29', 27, 'shop', 'search product', 'търси продукт');
insert into Privilege(id, lastModifiedDate, code, entityArea, description, descriptionBg) values(29, '2011-09-29', 28, 'user', 'search user', 'търси потребител');
SET FOREIGN_KEY_CHECKS=1;
